apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: graphlab-mpijob
spec:
  slotsPerWorker: ${SLOTS_PER_WORKER}          
  runPolicy:
    cleanPodPolicy: None
    ttlSecondsAfterFinished: 120
  sshAuthMountPath: /home/mpiuser/.ssh

  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: hadoop-config
              configMap:
                name: my-hadoop-cluster-hadoop   
            - name: scratch
              emptyDir: {}
            - name: graphlabdata
              hostPath:
                path: ${HOST_PATH}
                type: Directory
            - name: shared-mpi-data
              emptyDir: {}

            
          containers:
            - name: mpi-launcher
              image: graphlab-mpi:v0.1      
              imagePullPolicy: IfNotPresent
              securityContext:
                runAsUser: 1000
              env:
                - name: HADOOP_CONF_DIR
                  value: "/etc/hadoop"

                - name: HDFS_NN_SERVICE
                  value: my-hadoop-cluster-hadoop-hdfs-nn
                - name: HDFS_NN_PORT
                  value: "9000"                   

                - name: CLEAN_OUTPUT
                  value: "1"

                - name: JAVA_HOME
                  value: /usr/lib/jvm/java-17-openjdk-amd64
                - name: PATH
                  value: "$(JAVA_HOME)/bin:/usr/local/hadoop/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"


              volumeMounts:
                - name: hadoop-config
                  mountPath: /etc/hadoop
                - name: scratch
                  mountPath: /opt/scratch
                - name: graphlabdata
                  mountPath: /opt/data/
                - name: shared-mpi-data
                  mountPath: /mnt/mpi

              command: ["/bin/bash"]
              args:
                - "-c"
                - |
                    # 开启调试模式，如果任何命令失败则立即退出
                    # set -euxo pipefail # <- 修正了拼写

                    echo "[INFO] Waiting 10s for network/DNS to fully ready..."
                    sleep 10

                    HADOOP_CP=$(cat /etc/hadoop_classpath)

                    CONVERTED_HOSTFILE="/mnt/mpi/hostfile" 
                    sed 's/ slots=/:/' /etc/mpi/hostfile > "${CONVERTED_HOSTFILE}"

                    if [ "${ALGORITHM}" == "pagerank" ]; then
                      time mpiexec \
                        -n ${REPLICAS} \
                        --hostfile /etc/mpi/hostfile \
                        -verbose \
                        -x CLASSPATH="$HADOOP_CP" \
                        -x LD_LIBRARY_PATH="/usr/lib/jvm/java-17-openjdk-amd64/lib/server:/usr/local/hadoop/lib/native:/usr/local/bin:/usr/local/lib:/opt/mpich/lib/:/usr/local/openmpi/bin:/usr/local/openmpi/lib" \
                        -x JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64" \
                        -x HADOOP_CONF_DIR="/etc/hadoop" \
                        /opt/graphlab/release/toolkits/graph_analytics/${ALGORITHM} --iterations=10 --format=snap \
                        --graph /opt/data/${DATASET}
                    elif [ "${ALGORITHM}" == "sssp" ]; then
                      time mpiexec \
                        -n ${REPLICAS} \
                        --hostfile /etc/mpi/hostfile \
                        -verbose \
                        -x CLASSPATH="$HADOOP_CP" \
                        -x LD_LIBRARY_PATH="/usr/lib/jvm/java-17-openjdk-amd64/lib/server:/usr/local/hadoop/lib/native:/usr/local/bin:/usr/local/lib:/opt/mpich/lib/:/usr/local/openmpi/bin:/usr/local/openmpi/lib" \
                        -x JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64" \
                        -x HADOOP_CONF_DIR="/etc/hadoop" \
                        /opt/graphlab/release/toolkits/graph_analytics/${ALGORITHM} --source=0 --format=snap \
                        --graph /opt/data/${DATASET}

                    elif [ "${ALGORITHM}" == "triangle_count" ]; then

                      time mpiexec \
                        -n ${REPLICAS} \
                        --hostfile /etc/mpi/hostfile \
                        -verbose \
                        -x CLASSPATH="$HADOOP_CP" \
                        -x LD_LIBRARY_PATH="/usr/lib/jvm/java-17-openjdk-amd64/lib/server:/usr/local/hadoop/lib/native:/usr/local/bin:/usr/local/lib:/opt/mpich/lib/:/usr/local/openmpi/bin:/usr/local/openmpi/lib" \
                        -x JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64" \
                        -x HADOOP_CONF_DIR="/etc/hadoop" \
                        /opt/graphlab/release/toolkits/graph_analytics/undirected_triangle_count --format=snap \
                        --graph /opt/data/${DATASET}


                    elif [ "${ALGORITHM}" == "lpa" ]; then

                      time mpiexec \
                        -n ${REPLICAS} \
                        --hostfile /etc/mpi/hostfile \
                        -verbose \
                        -x CLASSPATH="$HADOOP_CP" \
                        -x LD_LIBRARY_PATH="/usr/lib/jvm/java-17-openjdk-amd64/lib/server:/usr/local/hadoop/lib/native:/usr/local/bin:/usr/local/lib:/opt/mpich/lib/:/usr/local/openmpi/bin:/usr/local/openmpi/lib" \
                        -x JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64" \
                        -x HADOOP_CONF_DIR="/etc/hadoop" \
                        /opt/graphlab/release/toolkits/graph_analytics/label_propagation --format=snap \
                        --graph /opt/data/${DATASET}


                    elif [ "${ALGORITHM}" == "kcore" ]; then

                      time mpiexec \
                        -n ${REPLICAS} \
                        --hostfile /etc/mpi/hostfile \
                        -verbose \
                        -x CLASSPATH="$HADOOP_CP" \
                        -x LD_LIBRARY_PATH="/usr/lib/jvm/java-17-openjdk-amd64/lib/server:/usr/local/hadoop/lib/native:/usr/local/bin:/usr/local/lib:/opt/mpich/lib/:/usr/local/openmpi/bin:/usr/local/openmpi/lib" \
                        -x JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64" \
                        -x HADOOP_CONF_DIR="/etc/hadoop" \
                        /opt/graphlab/release/toolkits/graph_analytics/kcore --format=snap --kmin 1 --kmax 3600000 \
                        --graph /opt/data/${DATASET}


                    elif [ "${ALGORITHM}" == "connected_component" ]; then

                      time mpiexec \
                        -n ${REPLICAS} \
                        --hostfile /etc/mpi/hostfile \
                        -verbose \
                        -x CLASSPATH="$HADOOP_CP" \
                        -x LD_LIBRARY_PATH="/usr/lib/jvm/java-17-openjdk-amd64/lib/server:/usr/local/hadoop/lib/native:/usr/local/bin:/usr/local/lib:/opt/mpich/lib/:/usr/local/openmpi/bin:/usr/local/openmpi/lib" \
                        -x JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64" \
                        -x HADOOP_CONF_DIR="/etc/hadoop" \
                        /opt/graphlab/release/toolkits/graph_analytics/connected_component --format=snap \
                        --graph /opt/data/${DATASET}

                    elif [ "${ALGORITHM}" == "bc" ]; then

                      time mpiexec \
                        -n ${REPLICAS} \
                        --hostfile /etc/mpi/hostfile \
                        -verbose \
                        -x CLASSPATH="$HADOOP_CP" \
                        -x LD_LIBRARY_PATH="/usr/lib/jvm/java-17-openjdk-amd64/lib/server:/usr/local/hadoop/lib/native:/usr/local/bin:/usr/local/lib:/opt/mpich/lib/:/usr/local/openmpi/bin:/usr/local/openmpi/lib" \
                        -x JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64" \
                        -x HADOOP_CONF_DIR="/etc/hadoop" \
                        /opt/graphlab/release/toolkits/graph_analytics/betweenness --format=snap \
                        --graph /opt/data/${DATASET}


                    else
                      echo "[ERROR] Unknown algorithm: ${ALGORITHM}"
                    fi

              resources:
                limits:
                  cpu: ${CPU}
                  memory: ${MEMORY}
                requests:
                  cpu: ${CPU}
                  memory: ${MEMORY}

    Worker:
      replicas: ${REPLICAS}
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: hadoop-config
              configMap:
                name: my-hadoop-cluster-hadoop
            - name: scratch
              emptyDir: {}
            - name: graphlabdata
              hostPath:
                path: ${HOST_PATH}
                type: Directory
            - name: shared-mpi-data
              emptyDir: {}
          containers:
            - name: mpi-worker
              image: graphlab-mpi:v0.1    
              imagePullPolicy: IfNotPresent
              securityContext:
                runAsUser: 1000
              env:
                - name: JAVA_HOME
                  value: /usr/lib/jvm/java-17-openjdk-amd64
                - name: PATH
                  value: "$(JAVA_HOME)/bin:/usr/local/hadoop/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
                - name: HADOOP_CONF_DIR
                  value: "/etc/hadoop"
                - name: HDFS_NN_SERVICE
                  value: my-hadoop-cluster-hadoop-hdfs-nn
                - name: HDFS_NN_PORT
                  value: "9000"  


              volumeMounts:
                - name: hadoop-config
                  mountPath: /etc/hadoop
                - name: scratch
                  mountPath: /opt/scratch
                - name: graphlabdata
                  mountPath: /opt/data/
                - name: shared-mpi-data
                  mountPath: /mnt/mpi
              command: ["/usr/sbin/sshd"]
              args: ["-De","-f","/home/mpiuser/.sshd_config"]
              resources:
                limits:
                  cpu: ${CPU}
                  memory: ${MEMORY}
                requests:
                  cpu: ${CPU}
                  memory: ${MEMORY}
