apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: ligra-mpijob
spec:
  slotsPerWorker: ${SLOTS_PER_WORKER}
  runPolicy:
    cleanPodPolicy: None
    ttlSecondsAfterFinished: 60
  sshAuthMountPath: /home/mpiuser/.ssh
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          ${VOLUMES_BLOCK}
          containers:
          - image: graphanalysisbenchmarks/ligra-mpi:v0.1
            name: mpi-launcher
            securityContext:
              runAsUser: 1000
            ${VOLUME_MOUNTS_BLOCK}
            command: ["/bin/bash", "-c"]
            args:
              - |
                set -e
                echo "[INFO] Waiting for DNS sync..."; sleep 5;
                if [ "${ALGORITHM}" = "BellmanFord" ]; then
                  time ./${ALGORITHM}${MPIRUN_NP} -rounds 1 /opt/data/graph_sssp.txt
                else
                  time ./${ALGORITHM}${MPIRUN_NP} -rounds 1 /opt/data/graph.txt
                fi
                
            resources:
              limits:
                cpu: ${CPU}
                memory: ${MEMORY}
    Worker:
      replicas: ${REPLICAS}
      template:
        spec:
          ${VOLUMES_BLOCK}
          containers:
          - image: graphanalysisbenchmarks/ligra-mpi:v0.1
            name: mpi-worker
            securityContext:
              runAsUser: 1000
            ${VOLUME_MOUNTS_BLOCK}
            command:
            - /usr/sbin/sshd
            args:
            - -De
            - -f
            - /home/mpiuser/.sshd_config
            resources:
              limits:
                cpu: ${CPU}
                memory: ${MEMORY}
